### ISSUE TITLE
Update Geofabric Dataset to present DCAT metadata

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/ld.cat#1]
As discussed, we need to be able to get dcat.ttl from linked.data.gov.au/dataset/geofabric (Accept: text/turtle) as _view=dcat is the default view. Also needing implementation are the reg & void views for Geofabric, just like GNAF & ASGS.

All the resources you need are in the GNAF API for copy 'n paste.

**Comment by edmondchuc** [comment]
Other views work, need to finish the VoiD view.

**Comment by edmondchuc** [comment]
Completed VoiD view.
