### ISSUE TITLE
Fix broken image links on loci.cat website

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#15]
Images on https://loci.cat are broken. Would be good to fix these.

**Comment by dr-shorthair** [comment]
Yes - we need a good landing page about the project to show to outsiders.

**Comment by jyucsiro** [comment]
The previous loci.cat site seems to be a full web application (python?).

In looking into the broken images (which don't appear to be checked in to the git repo), I'm exploring switching over a Github pages approach, which doesn't involve maintaining VMs and a web server. 

Working towards refactoring content then switching the DNS entry to that. Interim site accessible here: https://csiro-enviro-informatics.github.io/loci.cat/ 

Code being committed in the `gh-pages` branch.

**Comment by dr-shorthair** [comment]
I see the top page is .md
Is the intention to convert the other linked pages - currently .html - also into markdown?

**Comment by dr-shorthair** [comment]
Oh - I see they already are. 
I guess I don't understand the way the links are built then ... 
Is this how github pages works??

**Comment by jyucsiro** [comment]
Yes. It can also reference .html files if need be, but let's go with markdown for now to be consistent across all pages. we have to add a header to create the permalink. other than that - it's straight markdown.

**Comment by dr-shorthair** [comment]
Good solution though.
