### ISSUE TITLE
Need a test dataset (extract from cache)

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/ld.cat#18]
For various use-cases it would be convenient to have a small, but fully representative, test dataset. 
This should be a spatial extract of the full Loc-I linked datasets all the feature-types and links between feature instances - e.g. ACT.

**Comment by dr-shorthair** [comment]
I'm often working in the dark on the ontology alignments and remediations without a test dataset guys.

**Comment by jyucsiro** [comment]
see also https://github.com/CSIRO-enviro-informatics/loci-testdata/pull/8
