### ISSUE TITLE
Create Landing Pages for Dataset, Linkset & Definitional Resource

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/ld.cat#2]
- [x] Ignore Tool for now and just put a static *Coming Soon!* response in the controller.py for now.

- [x] Present basic metadata from the dcat.ttl files in the three APIs for Dataset.

- [x] Present basic metadata for Linkset as per the demo linkset's header file (https://github.com/CSIRO-enviro-informatics/addressescatchments-linkset/blob/master/header.ttl).

- [x] Just present basic LODE metadata for Def. Res.

**Comment by edmondchuc** [comment]
*Coming soon!* gets rendered in any registers with zero items.

**Comment by edmondchuc** [comment]
*Coming soon!* gets rendered in any registers with zero items.
