### ISSUE TITLE
Switch loci.cat to point to gh-pages

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#31]
Currently loci.cat is maintained as a web server serving pages about the test site for loci. It currently has broken pages.

We have migrated content over to Github pages from the main loci.cat repo. This issue is to switch over serving of loci.cat from the web server to the GH pages version

**Comment by dr-shorthair** [comment]
Should `gh-pages` be the Default branch? 
![image](https://user-images.githubusercontent.com/608303/68823325-89f57b80-06e7-11ea-8cc6-439e9a0d30ec.png)

**Comment by jyucsiro** [comment]
yes i'm confident now to do so

**Comment by jyucsiro** [comment]
switched loci.cat to gh pages version now.
