### ISSUE TITLE
Look at fix for Chrome Accept header bug in various Loc-I pyLDAPI instances

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#42]
See https://github.com/RDFLib/pyLDAPI/issues/21

PR to be reviewed and implemented.

Fix needs to be patched into gnafld.net, asgsld.net, geofabricld.net

**Comment by ashleysommer** [comment]
closed by https://github.com/RDFLib/pyLDAPI/commit/68a8d2b9d4fdb85c276e6da570a9e0d0eac81125
