### ISSUE TITLE
Separate repository for Geometry Data Service

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/ld.cat#48]
GDS needs a standalone repo.

**Comment by jyucsiro** [comment]
@dr-shorthair we have 2 repos for GDS:
1. https://github.com/CSIRO-enviro-informatics/geometry-data-service
2. https://github.com/CSIRO-enviro-informatics/loci-geometry-data-service 

The latter uses the former but customises it to load geometries for Loc-I.

The first repo aims to be generic (although there might be some configs there localised for Loc-I). 

Is that what you mean?

**Comment by dr-shorthair** [comment]
Sorry - missed that. Confused about where the code is vs where the documentation is. 
I think GDS is likely to be a standalone product anyway, so we will need documentation over there, IMHO.  (i.e the basic description of GDS API should be there, not just installation instructions)

**Comment by dr-shorthair** [comment]
I'll close this issue and create one over there about documentation instead. 
https://github.com/CSIRO-enviro-informatics/geometry-data-service/issues/19
