### ISSUE TITLE
Determine location of DGGS enablement online APIs

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/ld.cat#64]
GA will host DGGS Engine Web API as per https://github.com/CSIRO-enviro-informatics/loci.cat/issues/59#issuecomment-627700377

Propose implementing as DGGS Engine Web API
* Flask + OpenAPI REST interface to Auspix_DGGS lib (bindings to swagger/openapi via https://github.com/python-restx/flask-restx or https://github.com/flasgger/flasgger)
* Docker container to easily deploy

**Comment by jyucsiro** [comment]
Flask is proposed here (vs Sanic) as a more widely used framework and we don't require async features.

Deployment can be direct via Python or via docker as a widely accepted way to deploy python apps.

Developing the web api at https://github.com/CSIRO-enviro-informatics/AusPIX_DGGS_API and can transition ownership to GA in due time.

**Comment by bellie888** [comment]
Talking to Irina this morning a Docker container method was discussed with Will and Shane and it was "approved" as a suitable method.

**Comment by jyucsiro** [comment]
Devops via Terraform and Packer
